# ---------------------------------------------------------------------------------------------
# MIT License
#
# Copyright (c) 2020, Solace Corporation, Ricardo Gomez-Ulmke (ricardo.gomez-ulmke@solace.com)
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
# ---------------------------------------------------------------------------------------------

-
  name: "Integration Test: solace_bridges"
  hosts: "{{ brokers }}"
  gather_facts: no
  #any_errors_fatal: true
  module_defaults:
    solace_gather_facts:
      host: "{{ sempv2_host }}"
      port: "{{ sempv2_port }}"
      secure_connection: "{{ sempv2_is_secure_connection }}"
      username: "{{ sempv2_username }}"
      password: "{{ sempv2_password }}"
      timeout: "{{ sempv2_timeout }}"
      solace_cloud_api_token: "{{ solace_cloud_api_token | default(omit) }}"
      solace_cloud_service_id: "{{ solace_cloud_service_id | default(omit) }}"
    solace_get_bridges:
      host: "{{ sempv2_host }}"
      port: "{{ sempv2_port }}"
      secure_connection: "{{ sempv2_is_secure_connection }}"
      username: "{{ sempv2_username }}"
      password: "{{ sempv2_password }}"
      timeout: "{{ sempv2_timeout }}"
    solace_get_bridge_remote_vpns:
      host: "{{ sempv2_host }}"
      port: "{{ sempv2_port }}"
      secure_connection: "{{ sempv2_is_secure_connection }}"
      username: "{{ sempv2_username }}"
      password: "{{ sempv2_password }}"
      timeout: "{{ sempv2_timeout }}"
    solace_client_username:
      host: "{{ sempv2_host }}"
      port: "{{ sempv2_port }}"
      secure_connection: "{{ sempv2_is_secure_connection }}"
      username: "{{ sempv2_username }}"
      password: "{{ sempv2_password }}"
      timeout: "{{ sempv2_timeout }}"
    solace_queue:
      host: "{{ sempv2_host }}"
      port: "{{ sempv2_port }}"
      secure_connection: "{{ sempv2_is_secure_connection }}"
      username: "{{ sempv2_username }}"
      password: "{{ sempv2_password }}"
      timeout: "{{ sempv2_timeout }}"
    solace_queue_subscription:
      host: "{{ sempv2_host }}"
      port: "{{ sempv2_port }}"
      secure_connection: "{{ sempv2_is_secure_connection }}"
      username: "{{ sempv2_username }}"
      password: "{{ sempv2_password }}"
      timeout: "{{ sempv2_timeout }}"
    solace_bridge:
      host: "{{ sempv2_host }}"
      port: "{{ sempv2_port }}"
      secure_connection: "{{ sempv2_is_secure_connection }}"
      username: "{{ sempv2_username }}"
      password: "{{ sempv2_password }}"
      timeout: "{{ sempv2_timeout }}"
    solace_bridge_remote_vpn:
      host: "{{ sempv2_host }}"
      port: "{{ sempv2_port }}"
      secure_connection: "{{ sempv2_is_secure_connection }}"
      username: "{{ sempv2_username }}"
      password: "{{ sempv2_password }}"
      timeout: "{{ sempv2_timeout }}"
    solace_bridge_tls_cn:
      host: "{{ sempv2_host }}"
      port: "{{ sempv2_port }}"
      secure_connection: "{{ sempv2_is_secure_connection }}"
      username: "{{ sempv2_username }}"
      password: "{{ sempv2_password }}"
      timeout: "{{ sempv2_timeout }}"
    solace_bridge_remote_subscription:
      host: "{{ sempv2_host }}"
      port: "{{ sempv2_port }}"
      secure_connection: "{{ sempv2_is_secure_connection }}"
      username: "{{ sempv2_username }}"
      password: "{{ sempv2_password }}"
      timeout: "{{ sempv2_timeout }}"

  tasks:

    - name: Gather Solace Facts
      solace_gather_facts:

    - name: "Remove Bridge to ensure test starts clean"
      solace_bridge:
        name: "ansible-solace__test_bridge"
        msg_vpn: "{{ vpn }}"
        virtual_router: auto
        state: absent

    - name: Get List of all Bridges
      solace_get_bridges:
        msg_vpn: "{{ vpn }}"
        query_params:
          where:
            - "bridgeName==ansible-solace__test_bridge"
          select:
      register: pre_existing_bridges

    - name: Print pre-existing Bridges
      debug:
        msg:
          - "pre-exising bridges:"
          - "{{ pre_existing_bridges.result_list }}"

    - name: Print count of pre-existing Bridges
      debug:
        msg: "pre-existing bridges, count= {{ pre_existing_bridges.result_list_count }}"

    - assert: { that: "pre_existing_bridges.result_list_count == 0" }

    - name: Create Client Username
      solace_client_username:
        name: "ansible-solace__test_bridge"
        msg_vpn: "{{ vpn }}"
        settings:
          password: "ansible-solace__test_bridge"
        state: present

    - name: Create Queue
      solace_queue:
        name: "ansible-solace__test_bridge"
        msg_vpn: "{{ vpn }}"
        settings:
          owner: "ansible-solace__test_bridge"
          permission: consume
          egressEnabled: true
          ingressEnabled: true
        state: present

    - name: Create Subscription on Queue
      solace_queue_subscription:
        msg_vpn: "{{ vpn }}"
        queue_name: "ansible-solace__test_bridge"
        topic: "ansible/solace/test/bridge/queue/>"
        state: present

    # import the topology inventory
    - include_vars:
        file: "./lib/bridges.topology.yml"
        name: bridges_topology

    - name: Create Bridge
      solace_bridge:
        name: "ansible-solace__test_bridge"
        msg_vpn: "{{ vpn }}"
        virtual_router: auto
        settings:
          enabled: false
          remoteAuthenticationBasicClientUsername: "ansible-solace__test_bridge"
          remoteAuthenticationBasicPassword: "ansible-solace__test_bridge"
          remoteAuthenticationScheme: basic
        state: present

    - name: Get the Remote Host Settings for the Bridge
      debug:
        msg:
          - "remote_host: {{ bridges_topology.bridges['ansible-solace__test_bridge'][inventory_hostname].remote_host }}"
          - "remote_vpn: {{ bridges_topology.bridges['ansible-solace__test_bridge'][inventory_hostname].remote_vpn }}"

    - name: "Get Remote Host Bridge Facts"
      solace_get_facts:
        hostvars: "{{ hostvars }}"
        host: "{{ bridges_topology.bridges['ansible-solace__test_bridge'][inventory_hostname].remote_host }}"
        fields:
        field_funcs:
          - get_bridge_remoteMsgVpnLocations
      register: remote_host_bridge

    - name: Print Remote Host Bridge Facts
      debug:
        msg:
          - "remote host bridge facts:"
          - "{{ remote_host_bridge.facts }}"

    - name: Add Remote Message VPN to Bridge
      solace_bridge_remote_vpn:
        msg_vpn: "{{ vpn }}"
        bridge_name: "ansible-solace__test_bridge"
        bridge_virtual_router: auto
        remote_msg_vpn_name: "{{ bridges_topology.bridges['ansible-solace__test_bridge'][inventory_hostname].remote_vpn }}"
        # choose the correct remote location depending on the settings.tlsEnabled, settings.compressedDataEnabled
        remote_vpn_location: "{{ remote_host_bridge.facts.bridge_remoteMsgVpnLocations.plain }}"
        settings:
          enabled: false
          tlsEnabled: false
          compressedDataEnabled: false
        state: present

    - name: Update Remote Message VPN of Bridge
      solace_bridge_remote_vpn:
        msg_vpn: "{{ vpn }}"
        bridge_name: "ansible-solace__test_bridge"
        bridge_virtual_router: auto
        remote_msg_vpn_name: "{{ bridges_topology.bridges['ansible-solace__test_bridge'][inventory_hostname].remote_vpn }}"
        # choose the correct remote location depending on the settings.tlsEnabled, settings.compressedDataEnabled
        remote_vpn_location: "{{ remote_host_bridge.facts.bridge_remoteMsgVpnLocations.plain }}"
        settings:
          queueBinding: "ansible-solace__test_bridge"
        state: present

    - name: Enable Remote Message VPN of Bridge
      solace_bridge_remote_vpn:
        msg_vpn: "{{ vpn }}"
        bridge_name: "ansible-solace__test_bridge"
        bridge_virtual_router: auto
        remote_msg_vpn_name: "{{ bridges_topology.bridges['ansible-solace__test_bridge'][inventory_hostname].remote_vpn }}"
        # choose the correct remote location depending on the settings.tlsEnabled, settings.compressedDataEnabled
        remote_vpn_location: "{{ remote_host_bridge.facts.bridge_remoteMsgVpnLocations.plain }}"
        settings:
          enabled: true
        state: present

    # TODO
    # - name: Add Trusted Common Name to Bridge
    #     solace_bridge_tls_cn:


    - name: Add Remote Subscription DA to Bridge
      solace_bridge_remote_subscription:
        msg_vpn: "{{ vpn }}"
        bridge_name: "ansible-solace__test_bridge"
        bridge_virtual_router: auto
        remote_subscription_topic: "ansible/solace/test/bridge/da/>"
        settings:
          deliverAlwaysEnabled: true
        state: present

    - name: Add Remote Subscription P1 to Bridge
      solace_bridge_remote_subscription:
        msg_vpn: "{{ vpn }}"
        bridge_name: "ansible-solace__test_bridge"
        bridge_virtual_router: auto
        remote_subscription_topic: "ansible/solace/test/bridge/p1/>"
        settings:
          deliverAlwaysEnabled: false
        state: present

    - name: Enable Bridge
      solace_bridge:
        name: "ansible-solace__test_bridge"
        msg_vpn: "{{ vpn }}"
        virtual_router: auto
        settings:
          enabled: true
        state: present

    - meta: end_play

    - name: "Check: Bridge Remote VPN is UP"
      solace_get_bridge_remote_vpns:
        msg_vpn: "{{ vpn }}"
        bridge_name: ansible-solace__test_bridge
        api: monitor
        query_params:
          where:
          select:
            - bridgeName
            - remoteMsgVpnLocation
            - enabled
            - up
            - lastConnectionFailureReason
            - compressedDataEnabled
            - tlsEnabled
      register: bridge_remote_vpn_monitor_list

    - name: Print Bridge Remote VPNs Monitoring Info
      debug:
        msg:
          - "bridge remote VPN monitor info:"
          - "{{ bridge_remote_vpn_monitor_list.result_list[0] }}"

    - name: Assert Bridge Remote VPN Up
      fail:
        msg:
          - "ERROR: Bridge Remote VPN not up."
          - "remote vpn info:"
          - "{{ bridge_remote_vpn_monitor_list.result_list[0] }}"
      when: bridge_remote_vpn_monitor_list.result_list[0].up == false

    - name: "Check & Retry: Bridge is UP"
      solace_get_bridges:
        msg_vpn: "{{ vpn }}"
        api: monitor
        query_params:
          where:
            - "bridgeName==ansible-solace__test_bridge"
          select:
            - inboundState
            - inboundFailureReason
            - outboundState
      register: bridge_list
      until:
        - bridge_list.result_list[0].inboundState == 'ready-in-sync'
        - bridge_list.result_list[0].outboundState == 'ready'
      retries: 3
      delay: 2
      ignore_errors: yes

    - name: Get Bridge Monitoring Info
      solace_get_bridges:
        msg_vpn: "{{ vpn }}"
        api: monitor
        query_params:
          where:
            - "bridgeName==ansible-solace__test_bridge"
          select:
            - boundToQueue
            - bridgeName
            - clientName
            - compressed
            - enabled
            - encrypted
            - establisher
            - localInterface
            - localQueueName
            - inboundFailureReason
            - inboundState
            - outboundState
            - remoteAddress
            - remoteRouterName
      register: bridge_list

    - name: Print Bridge Monitoring Info
      debug:
        msg:
          - "bridge_monitor:"
          - "{{ bridge_list.result_list[0] }}"

    - name: Assert Bridge Up
      fail:
        msg:
          - "ERROR: bridge not up."
          - "inboundState: {{ bridge_list.result_list[0].inboundState }}"
          - "inboundFailureReason: {{ bridge_list.result_list[0].inboundFailureReason | default('') }}"
          - "outboundState: {{ bridge_list.result_list[0].outboundState | default('') }}"
      when: >
        bridge_list.result_list[0].inboundState != 'ready-in-sync' or
        bridge_list.result_list[0].outboundState != 'ready'


  # Remove all the objects created

    - name: Remove Remote Subscription DA from Bridge
      solace_bridge_remote_subscription:
        msg_vpn: "{{ vpn }}"
        bridge_name: "ansible-solace__test_bridge"
        bridge_virtual_router: auto
        remote_subscription_topic: "ansible/solace/test/bridge/da/>"
        state: absent

    - name: Remove Remote Subscription P1 from Bridge
      solace_bridge_remote_subscription:
        msg_vpn: "{{ vpn }}"
        bridge_name: "ansible-solace__test_bridge"
        bridge_virtual_router: auto
        remote_subscription_topic: "ansible/solace/test/bridge/p1/>"
        state: absent

    - name: Remove Queue Binding from Remote Message VPN of Bridge
      solace_bridge_remote_vpn:
        msg_vpn: "{{ vpn }}"
        bridge_name: "ansible-solace__test_bridge"
        bridge_virtual_router: auto
        remote_msg_vpn_name: "{{ bridges_topology.bridges['ansible-solace__test_bridge'][inventory_hostname].remote_vpn }}"
        # choose the correct remote location depending on the settings.tlsEnabled, settings.compressedDataEnabled
        remote_vpn_location: "{{ remote_host_bridge.facts.bridge_remoteMsgVpnLocations.plain }}"
        settings:
          queueBinding: ""
        state: present

    - name: Remove Remote Message VPN from Bridge
      solace_bridge_remote_vpn:
        msg_vpn: "{{ vpn }}"
        bridge_name: "ansible-solace__test_bridge"
        bridge_virtual_router: auto
        remote_msg_vpn_name: "{{ bridges_topology.bridges['ansible-solace__test_bridge'][inventory_hostname].remote_vpn }}"
        # choose the correct remote location depending on the settings.tlsEnabled, settings.compressedDataEnabled
        remote_vpn_location: "{{ remote_host_bridge.facts.bridge_remoteMsgVpnLocations.plain }}"
        state: absent

    - name: Remove Bridge
      solace_bridge:
        name: "ansible-solace__test_bridge"
        msg_vpn: "{{ vpn }}"
        virtual_router: auto
        state: absent

    - name: Remove Queue
      solace_queue:
        name: "ansible-solace__test_bridge"
        msg_vpn: "{{ vpn }}"
        state: absent

    - name: Remove Client Username
      solace_client_username:
        name: "ansible-solace__test_bridge"
        msg_vpn: "{{ vpn }}"
        state: absent

###
# The End.
