
# ---------------------------------------------------------------------------------------------
# MIT License
#
# Copyright (c) 2020, Solace Corporation, Ricardo Gomez-Ulmke (ricardo.gomez-ulmke@solace.com)
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
# ---------------------------------------------------------------------------------------------

-
  name: "Exception_Test_2: solace_cloud_service"
  hosts: "{{ SOLACE_CLOUD_ACCOUNTS }}"
  gather_facts: no
  any_errors_fatal: true

  tasks:

    # DEBUG
    # - meta: end_play

    # serviceTypeId: developer=single, enterprise=HA
    # serviceTypeId = developer -> serviceClassId = developer
    # serviceTypeId = enterprise -> serviceClassId = enterprise-250-nano, enterprise-kilo, enterprise-mega, enterprise-giga, enterprise-tera, enterprise-100k-tera

    - name: "Exception_Test: no name, state=present"
      solace_cloud_service:
        api_token: "{{ api_token_all_permissions }}"
        # name: this-service-should-never-be-created
        settings:
          msgVpnName: "not-created-vpn"
          datacenterId: "aws-eu-west-2a"
          serviceTypeId: "enterprise"
          serviceClassId: "enterprise-giga"
        state: present
      register: result
      failed_when: "result.rc != 1"

    - name: "Exception_Test: no name, state=absent"
      solace_cloud_service:
        api_token: "{{ api_token_all_permissions }}"
        # name: this-service-should-never-be-created
        state: absent
      register: result
      failed_when: "result.rc != 1"

    - name: "Exception_Test: wrong service_id, state=absent"
      solace_cloud_service:
        api_token: "{{ api_token_all_permissions }}"
        # name: this-service-should-never-be-created
        service_id: xxxxx
        state: absent
      register: result
      failed_when: "result.rc != 1"

    - name: "Exception_Test: Plan not available"
      solace_cloud_service:
        api_token: "{{ api_token_all_permissions }}"
        name: this-service-should-never-be-created
        settings:
          msgVpnName: "not-created-vpn"
          datacenterId: "aws-eu-west-2a"
          serviceTypeId: "enterprise"
          serviceClassId: "enterprise-giga"
        state: present
      register: result
      failed_when: "result.rc != 1"

    - name: "Exception_Test: Token has no permissions"
      solace_cloud_service:
        api_token: "{{ api_token_restricted_permissions }}"
        name: never-created-service
        settings:
          msgVpnName: "not-created-vpn"
          datacenterId: "aws-eu-west-2a"
          serviceTypeId: "enterprise"
          serviceClassId: "enterprise-250-nano"
        state: present
      register: result
      failed_when: "result.rc != 1"

    - name: "Exception_Test: not a token"
      solace_cloud_service:
        api_token: "xxxx-yyyy"
        name: never-created-service
        settings:
          msgVpnName: "not-created-vpn"
          datacenterId: "aws-eu-west-2a"
          serviceTypeId: "enterprise"
          serviceClassId: "enterprise-250-nano"
        state: present
      register: result
      failed_when: "result.rc != 1"

    - name: "Exception_Test: no settings"
      solace_cloud_service:
        api_token: "{{ api_token_all_permissions }}"
        name: this-service-should-never-be-created
        # settings:
        #   msgVpnName: "not-created-vpn"
        #   datacenterId: "aws-eu-west-2a"
        #   serviceTypeId: "enterprise"
        #   serviceClassId: "enterprise-giga"
        state: present
      register: result
      failed_when: "result.rc != 1"

    - name: "Exception_Test: empty settings"
      solace_cloud_service:
        api_token: "{{ api_token_all_permissions }}"
        name: this-service-should-never-be-created
        settings:
        #   msgVpnName: "not-created-vpn"
        #   datacenterId: "aws-eu-west-2a"
        #   serviceTypeId: "enterprise"
        #   serviceClassId: "enterprise-giga"
        state: present
      register: result
      failed_when: "result.rc != 1"

    - name: "Exception_Test: insufficient settings"
      solace_cloud_service:
        api_token: "{{ api_token_all_permissions }}"
        name: this-service-should-never-be-created
        settings:
          msgVpnName: "not-created-vpn"
        #   datacenterId: "aws-eu-west-2a"
        #   serviceTypeId: "enterprise"
        #   serviceClassId: "enterprise-giga"
        state: present
      register: result
      failed_when: "result.rc != 1"


###
# The End.
